version: '2'

services:
  crawler:
    build:
      context: crawler
      dockerfile: Dockerfile
    volumes:
      - './crawler:/app'
  elasticsearch:
    image: 'amazon/opendistro-for-elasticsearch:1.12.0'
    environment:
      - 'discovery.type=single-node'
    ports:
      - '9200:9200'
      - '9300:9300'
